export default {
  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNUP: "USER_SIGNUP",
  USER_STATUS: "USER_STATUS",
  USER_INFO: "USER_INFO",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILURE: "USER_SIGNIN_FAILURE",
  GET_ACCOUNT_LIST: "GET_ACCOUNT_LIST",
  ACCOUNT_DATALIST: "ACCOUNT_DATALIST",
  ACCOUNT_USER: "ACCOUNT_USER",
  SEND_MESSAGE: "SEND_MESSAGE",
  ADD_MESSAGE_LIST: "ADD_MESSAGE_LIST",
  RECEIVED_MESSAGE: "RECEIVED_MESSAGE",
  FILTER_ACCOUNT: "FILTER_ACCOUNT",
  EDIT_ACCOUNT: "EDIT_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT"
};
