export default {
  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNUP: "USER_SIGNUP",
  USER_STATUS: "USER_STATUS",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILURE: "USER_SIGNIN_FAILURE"
};
